service: lambda-slack-menu

frameworkVersion: "^3.3.0"

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-deployment-bucket
custom:
  stage: ${opt:stage, "prod"}
  prune:
    automatic: true
    number: 20
  dotenv:
    path: .env
  capacities:
    - table: MenuTable  # DynamoDB Resource
      read:
        minimum: 1        # Minimum read capacity
        maximum: 1000     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 1       # Minimum write capacity
        maximum: 200      # Maximum write capacity
        usage: 0.5        # Targeted usage percentage

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  region: ap-northeast-2
  deploymentBucket:
    name: lambda-slack-menu-prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
        - dynamodb:*
      Resource: "*"

package:
  patterns:
    - 'resources/**'
    - '!./*yml'
    - '!.vscode/**'
    - '!.gitignore'
    - '!.git/**'
    - '!tsconfig*'
    - '!tslint.json'
    - '!yarn.lock'
    - '!.serverless/**'
    - '!Dockerfile*'
    - '!./docs/**'
    - '!./build/**'
    - '!./test/**'
    - '!./ci/**'
    - '!node_modules/serverless*'
  excludeDevDependencies: true

functions:
  menu:
    name: slack-menu
    handler: src/functions/menu/handler.main
    timeout: 30
    events:
      - http:
          path: menu
          method: post
  dynamodb-sample:
    name: dynamodb-sample
    handler: src/functions/dynamodb-sample/index.handler
    timeout: 30
    events:
      - http:
          path: dynamodb-sample
          method: post

resources:
  Resources:
    # Dynamodb Table 생성
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MenuTable
        AttributeDefinitions:
          - AttributeName: menuDate
            AttributeType: S
          - AttributeName: menuTime
            AttributeType: S
        KeySchema:
          - AttributeName: menuDate
            KeyType: HASH
          - AttributeName: menuTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
